version: '3.4'

services:
  postgres:
    build:
      context: './db'
      dockerfile: 'Dockerfile'
    container_name: 'db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exchange_bot_development
    ports:
      - '5444:5432'
    volumes:
      - ./.tmp/db:/var/lib/postgresql/data
